# Persistent Volume Claim (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xdoc-pvc-claim
  namespace: xdoc-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: xdoc-pvc
---
# StorageClass (example using NFS)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: xdoc-pvc
  namespace: xdoc-system
provisioner: kubernetes.io/nfs
parameters:
  path: /codx-file-storage/files
  server: 192.168.18.36