kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-nfs-pv-claim
  namespace: minio-nfs

spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi