apiVersion: v1
kind: Namespace
metadata:
  name: jupyter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
  namespace: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook 

    spec:
      containers:
      - name: jupyter-notebook
        image: jupyter/notebook
        ports:
        - containerPort: 8888
        env:
        - name: JUPYTER_PASSWORD
          value: your_password
        - name: PASSWORD
          value: 123456
        volumeMounts:
        - name: notebook-data
          mountPath: /home/jovyan/work
      volumes:
        - name: notebook-data
          nfs:
            server: 192.168.18.36
            path: /codx-file-storage/files/jupyter
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-notebook-service
  namespace: jupyter
spec:
  selector:
    app: jupyter-notebook
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: NodePort