#0-myminio-pool-0-0
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 0-myminio-pool-0-0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storageclass
  resources:
    requests:
      storage: 2Gi